version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
