version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
        environment:
          RAILS_ENV: test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.32
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Which bundle?
          command: bundle -v
      - ruby/rubocop-check:
          format: progress
          label: Rubocop inspecting

      # Setup DB
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Test
      - ruby/rspec-test
