version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
  node: circleci/node@4.5.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-browsers
        environment:
            TZ: Asia/Tokyo
            RAILS_ENV: test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.32
        environment:
          TZ: Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - ruby/install-deps

      # Setup DB
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      
      # Test
      - ruby/rspec-test
