default: &default
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: DBMS#2021
  host: localhost

development:
  <<: *default
  database: phone_shop_development

test:
  <<: *default
  database: phone_shop_test

production:
  <<: *default
  database: phone_shop_production
  username: phone_shop
  password: <%= ENV['PHONE_SHOP_DATABASE_PASSWORD'] %>
